num.sim <- 500;
alajo.seq <- make.sequence(1,num.sim);
alajo.nw <- make.nw(alajo.seq,oov=FALSE,loops=FALSE);
bukom.seq <- make.sequence(2,num.sim);
bukom.nw <- make.nw(bukom.seq,oov=FALSE,loops=FALSE);
oldfadama.seq <- make.sequence(3,num.sim);
oldfadama.nw <- make.nw(oldfadama.seq,oov=FALSE,loops=FALSE);
shiabu.seq <- make.sequence(4,num.sim);
shiabu.nw <- make.nw(shiabu.seq,oov=FALSE,loops=FALSE);
